### DISCUSSION TITLE
How do I call sile when using GitHub Actions integration

### DISCUSSION THREAD

**Discussion by khaledhosny** [sile-typesetter/sile#1319] [Q&A] [answered]
I tried adding to my workflow file
```
   - name: The SILE Typesetter
      uses: sile-typesetter/sile@v0.12.2
```

But then my makefile can’t find sile (I need to use the makefile, since it does a bit of setup for the *.sil file). Any idea how to make sile available in the PATH when using it this way (if possible at all). I’m currently using the PPA version, and I was happy with it until I realized that it used an old HarfBuzz version that has a specific issue my project is hitting (so I really need an up to date HarfBuzz version)

**Comment by alerque** [comment, marked as answer]
The way the GitHub Action works it does not add `sile` to the path of the host container. It may be possible to setup a job that does that, but currently only the container based step is supported.

The best way to proceed probably depends on how much other work you need to do in various steps. The most likely two directions I see might be these (but there are other options, if you give me more info about what needs to happen I'll help find a way...)

1. Do your other work preparing the sil files first in other steps, then when the source file is ready to go, call the SILE action with the necessary path(s):

    ```yaml
    - name: Prepare sources
      run: make source_file.sil
    - name: The SILE Typesetter
      uses: sile-typesetter/sile@v0
      with:
        args: source_file.sil
    ```

2. Use the SILE image as your host container for the runner and install your other dependencies inside it:

    ```yaml
    container:
    runs-on: ubuntu-20.04
    image: sile-typesetter/sile@v0
      options: --entrypoint=bash
    steps:
    - name: Install dependencies
      run: pacman -S make
    - name: Build
      run: make
    ```

    In this scenario `sile` will be in the path and usable from your Makefile, but you will be in an Arch Linux container instead of an Ubuntu one.

    This method has the downside of *not* being able to run other GitHub action "steps" because the entire workflow is inside a docker container.

3. Run the SILE Docker build yourself by downloading the image into the default Ubuntu container yourself:

    ```yaml
    container:
    runs-on: ubuntu-20.04
    steps:
    - name: Fetch sile
      run: docker pull ghcr.io/sile-typesetter/sile:v0
    - name: Build
      run: |
        export SILE="docker run --volume '$(pwd):/data' --user '$(id -u):$(id -g)' sile-typesetter/sile:v0
        make
    ```

    Of course you'd want to use `$(SILE)` instead of `sile` in your Makefile for this arrangement.

If you need more complex tooling, there are more options, just let me know what the needs are.

**Reply by khaledhosny** [reply]
Thanks @alerque, these all are good suggestions and I’m sure one of them will work for me.

**Reply by alerque** [reply]
If none of these turn out to be a good easy match for your problem, do ping back here. As I mentioned in [another comment](https://github.com/sile-typesetter/sile/discussions/1319#discussioncomment-2250538) there are actually a couple more ways I didn't even think mention here that are actually quite easy and effective at getting up to date SILE/Harfbuzz/other software combinations available in a CI runner without even needing to build anything.

**Reply by alerque** [reply]
Also note I just noticed my shell quote nesting is probably wrong in example 3. It would depend on how you used it in the Makefile actually, and I did it that way because I often use ZSH with special expansion options but what is shown here probably won't work for bash. Use escaped double quotes (`\"`) instead of the nested single quotes (`'`) shown here.

**Reply by khaledhosny** [reply]
I’m completely new to docker, but `docker pull ghcr.io/sile-typesetter/sile@v0` fails with `invalid reference format` both on CI an locally.

**Reply by alerque** [reply]
Sorry wrong separator for that context, use `:` not `@` for the version. The GitHub Action YAML syntax for `uses:` uses at-sign separators, but Docker native commands use `:`.

**Reply by khaledhosny** [reply]
I ran into another issue, now with running SILE though docker `the input device is not a TTY`. I ended up using macOS on the CI, since that is what me and my collaborators use anyway (it is a font project, SILE is used to typeset sample files) and I get latest SILE and HarfBuzz from Homebrew. But I’ll keep the docker options if I need this for other projects.

**Reply by alerque** [reply]
Drop the `-it` flags from above, `-i` is interactive and `-t` is allocate a tty. Those are recommended for using the Docker image from a shell alias (where I copied from the readme), but are not appropriate for a CI job.

**Comment by simoncozens** [comment]
I'm a simple person. This is what my `build.yaml` looks like:

```yaml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Linux dependencies
      run: |
        sudo apt-get install libcairo2-dev libfreetype6-dev
        sudo add-apt-repository ppa:sile-typesetter/sile
        sudo apt-get update
        sudo apt-get install sile
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build font
      run: |
        make
    - name: Build specimen & proof
      run: sile specimen/specimen.sil
```
