### ISSUE TITLE
Unable to create several masters at once...

### ISSUE THREAD

**Issue by jodros** [sile-typesetter/sile#1804]
I wish to get the framesets from another file (e.g. a toml one):

```toml
[frames.right.first]
left = "(100%pw-50%ph)/2" 
right = "100%pw-((100%pw-50%ph)/2)" 
top = "(100%ph-100%pw)/2" 
bottom = "100%ph-((100%ph-100%pw)/2)"
 
[frames.right.runningHead]  
left = "3.4cm" 
right = "100%pw-2cm" 
top = "1.5cm" 
bottom = "top(content)-3%ph"

[frames.right.footnotes]
left = "left(content)"
right = "right(content)"
height = "0"
bottom = "90%ph"

[frames.right.folio]
left = "left(content)" 
right = "right(content)" 
top = "bottom(footnotes)+3%ph" 
bottom = "bottom(footnotes)+5%ph"

[frames.full.first] 
left = "0" 
right = "100%pw" 
top = "0" 
bottom = "100%ph"

[frames.cover.first]  
left = "25%pw" 
right = "75%pw" 
top = "20%ph" 
bottom = "30%ph"

[frames.cover.title]  
left = "30%pw" 
right = "70%pw" 
top = "45%ph" 
bottom = "55%ph"

[frames.cover.publisher]
left = "25%pw" 
right = "75%pw" 
top = "80%ph" 
bottom = "85%ph"
```

I am getting the parsing and table manipulation of this file in my lua code without any errors, except when I try to define a master for each frameset: 

```lua
for key, frame in pairs(config.frames) do
	print(inspect(frame["first"])) 

	self:defineMaster ({
		id = key,
		firstContentFrame = frame["first"],
		frames = frame
	})
end	
```

But I'm always getting:   

Using code at: /usr/share/sile/classes/base.lua:483: attempt to index a nil value (field 'firstContentFrame')

I can't understand why, since the print(inspect(frame["first"])) works fine, it shows the right frame for every frameset.

I've also tried: 

```lua
firstContentFrame = frame.first
```
and
```lua
firstContentFrame = "first"
```

None worked. I know that declaring each one explicitly would work, but my goal is to be able to handle any number of framesets one could declare in the toml file.
